# Site specific settings
title: "zcashblockexplorer.com"
name: "Zcash Block Explorer"
keywords: "zcash, block explorer, zec"
baseurl: "/"
url: "https://zcashblockexplorer.com"
description: "Defunct Zcash Block Explorer"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: true # It will redirect to https

# Media
# Just the shortname:
disqus: 
twitter: zcashexplorer
facebook: 
github: nighthawk-apps
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
